import type { Metadata } from "next";
import { Nunito, Quicksand } from "next/font/google";
import "./globals.css";

const quicksandFont = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"]
})
const nunitoFont = Nunito({
  variable: "--font-quicksand",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "-Cynix-",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksandFont.variable} ${nunitoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
