import { proxy } from "valtio";
type vec3_ = [number, number, number];

export type Wall = {
    colorStart: vec3_,
    colorEnd: vec3_,
    gradAngle: number,
    pattern: null | "circle" | "diamond",
    patternColor: "inverted-color-gradient" | number,
    patternStartScale: number,
    patternEndScale: number,
    patternBlur: number,
    patternAmount: number
}
export const wallState = proxy({
    roomWidth: 20,
    roomLength: 25,
    roomHeight: 10,
    topWall: {
        colorStart: rgb(216, 203, 182),
        colorEnd: rgb(225, 215, 198),
        pattern: null,
        gradAngle: 0,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    bottomWall: {
        colorStart: rgb(169, 149, 114),
        colorEnd: rgb(208, 185, 149),
        pattern: null,
        gradAngle: 0,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    leftWall: {
        colorStart: rgb(227, 207, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: null,
        gradAngle: 0,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    rightWall: {
        colorStart: rgb(227, 207, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: null,
        gradAngle: 180,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    frontWall: {
        colorStart: rgb(248, 224, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: null,
        gradAngle: 0,
        patternColor: .2,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    backWall: {
        colorStart: rgb(248, 224, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: "diamond",
        gradAngle: 0,
        patternColor: .2,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
});
function rgb(r: number, g: number, b: number) { return [r / 255, g / 255, b / 255] }