import { proxy } from "valtio";
type vec3_ = [number, number, number];

export type Wall = {
    colorStart: vec3_,
    colorEnd: vec3_,
    gradAngle: number,
    pattern: null | "circle" | "diamond" | "astroid",
    patternColor: "inverted-color-gradient" | number,
    patternStartScale: number,
    patternEndScale: number,
    patternBlur: number,
    patternAmount: number
}
export const wallState = proxy({
    roomWidth: 20,
    roomLength: 25,
    roomHeight: 10,
    topWall: {
        colorStart: rgb(216,182,198),
        colorEnd: rgb(215,167,189),
        pattern: "astroid",
        gradAngle: 0,
        patternColor: "inverted-color-gradient",
        patternStartScale: .5,
        patternEndScale: .5,
        patternBlur: .1,
        patternAmount: 20,
    } as Wall,
    bottomWall: {
        colorStart: rgb(169, 149, 114),
        colorEnd: rgb(208, 185, 149),
        pattern: null,
        gradAngle: 0,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .05,
        patternAmount: 20,
    } as Wall,
    leftWall: {
        colorStart: rgb(227, 207, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: null,
        gradAngle: 0,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .05,
        patternAmount: 20,
    } as Wall,
    rightWall: {
        colorStart: rgb(227, 207, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: null,
        gradAngle: 180,
        patternColor: .5,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .05,
        patternAmount: 20,
    } as Wall,
    frontWall: {
        colorStart: rgb(248, 224, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: "circle",
        gradAngle: 0,
        patternColor: .2,
        patternStartScale: 0,
        patternEndScale: .3,
        patternBlur: .05,
        patternAmount: 20,
    } as Wall,
    backWall: {
        colorStart: rgb(248, 224, 196),
        colorEnd: rgb(228, 208, 185),
        pattern: "diamond",
        gradAngle: 0,
        patternColor: .2,
        patternStartScale: .5,
        patternEndScale: 0,
        patternBlur: .05,
        patternAmount: 20,
    } as Wall,
    testCube: {
        colorStart: rgb(195,249,248),
        colorEnd: rgb(214,255,254),
        pattern: "diamond",
        gradAngle: 0,
        patternColor: .2,
        patternStartScale: .5,
        patternEndScale: .5,
        patternBlur: .05,
        patternAmount: 12,
    } as Wall,
});
function rgb(r: number, g: number, b: number) { return [r / 255, g / 255, b / 255] }